version: '3'
dotenv: ['.env', '.env.local']
tasks:
  default:
    desc: This help
    cmds:
      - task -a --sort none
    silent: true

  start:
    aliases: [s]
    deps:
      - build
    cmds:
      - node src/index.js

  build:
    dir: jobspy
    cmds: 
      - >
        docker build 
        --build-arg https_proxy=$https_proxy 
        --build-arg NODE_TLS_REJECT_UNAUTHORIZED=0
        -t jobspy .
